# https://taskfile.dev

version: '3'

tasks:
  aoc:*:*:prepare:
    desc: "Prepare files for Advent of Code"
    vars:
      DAY: '{{index .MATCH 0}}'
      YEAR: '{{index .MATCH 1}}'
    cmds:
      - docker compose exec app php artisan aoc:prepare {{.DAY}} {{.YEAR}}

  aoc:*:*:example:
    desc: "Run challenge"
    vars:
      DAY: '{{index .MATCH 0}}'
      YEAR: '{{index .MATCH 1}}'
    cmds:
      - docker compose exec app php artisan aoc:run {{.DAY}} {{.YEAR}} {{.PART}} --example

  aoc:*:*:run:
    desc: "Run challenge"
    vars:
      DAY: '{{index .MATCH 0}}'
      YEAR: '{{index .MATCH 1}}'
    cmds:
      - docker compose exec app php artisan aoc:run {{.DAY}} {{.YEAR}} {{.PART}}

  optimize:
    desc: "Run laravel optimize"
    cmds:
      - docker compose exec app php artisan optimize:clear
      - docker compose exec app php artisan optimize

  ecs:
    desc: "Run ECS checker"
    cmds:
      - docker compose exec app ./vendor/bin/ecs check .

  ecs:fix:
    desc: "Run ECS fixer"
    cmds:
      - docker compose exec app ./vendor/bin/ecs check . --fix

  build:
    desc: "Build Docker image"
    cmds:
      - docker build --no-cache -t local/aoc:latest .

  composer:install:
    desc: "Install Composer dependencies inside Docker"
    cmds:
      - docker compose exec app composer install

  composer:update:
    desc: "Install Composer dependencies inside Docker"
    cmds:
      - docker compose exec app composer update

  bash:
    desc: "Enter bash CLI"
    cmds:
      - docker compose exec app bash

  up:
    desc: "Start Docker containers (detached)"
    cmds:
      - docker compose up -d --force-recreate

  down:
    desc: "Stop Docker containers and remove them"
    cmds:
      - docker compose down -v

  init:
    desc: "Initialize dev environment (build, composer install, up)"
    cmds:
      - task: build
      - task: composer:install
      - task: up
