# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.8)
   message(FATAL_ERROR "CMake >= 2.8.0 required")
endif()
if(CMAKE_VERSION VERSION_LESS "2.8.3")
   message(FATAL_ERROR "CMake >= 2.8.3 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.8.3...3.26)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

if(CMAKE_VERSION VERSION_LESS 3.0.0)
  message(FATAL_ERROR "This file relies on consumers using CMake 3.0.0 or greater.")
endif()

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_cmake_targets_defined "")
set(_cmake_targets_not_defined "")
set(_cmake_expected_targets "")
foreach(_cmake_expected_target IN ITEMS GEOS::ryu GEOS::geos GEOS::geos_c GEOS::geos_cxx_flags GEOS::geos_developer_cxx_flags)
  list(APPEND _cmake_expected_targets "${_cmake_expected_target}")
  if(TARGET "${_cmake_expected_target}")
    list(APPEND _cmake_targets_defined "${_cmake_expected_target}")
  else()
    list(APPEND _cmake_targets_not_defined "${_cmake_expected_target}")
  endif()
endforeach()
unset(_cmake_expected_target)
if(_cmake_targets_defined STREQUAL _cmake_expected_targets)
  unset(_cmake_targets_defined)
  unset(_cmake_targets_not_defined)
  unset(_cmake_expected_targets)
  unset(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT _cmake_targets_defined STREQUAL "")
  string(REPLACE ";" ", " _cmake_targets_defined_text "${_cmake_targets_defined}")
  string(REPLACE ";" ", " _cmake_targets_not_defined_text "${_cmake_targets_not_defined}")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_cmake_targets_defined_text}\nTargets not yet defined: ${_cmake_targets_not_defined_text}\n")
endif()
unset(_cmake_targets_defined)
unset(_cmake_targets_not_defined)
unset(_cmake_expected_targets)


# Create imported target GEOS::ryu
add_library(GEOS::ryu OBJECT IMPORTED)

set_target_properties(GEOS::ryu PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/maciek/Personal/aoc/geos-3.14.1/src/deps"
)

# Create imported target GEOS::geos
add_library(GEOS::geos SHARED IMPORTED)

set_target_properties(GEOS::geos PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/maciek/Personal/aoc/geos-3.14.1/include;/home/maciek/Personal/aoc/geos-3.14.1/include;/home/maciek/Personal/aoc/geos-3.14.1/src/deps;/home/maciek/Personal/aoc/geos-3.14.1/src/deps"
  INTERFACE_LINK_LIBRARIES "GEOS::geos_cxx_flags"
)

# Create imported target GEOS::geos_c
add_library(GEOS::geos_c SHARED IMPORTED)

set_target_properties(GEOS::geos_c PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/maciek/Personal/aoc/geos-3.14.1/capi;/home/maciek/Personal/aoc/geos-3.14.1/capi;/home/maciek/Personal/aoc/geos-3.14.1/include"
)

# Create imported target GEOS::geos_cxx_flags
add_library(GEOS::geos_cxx_flags INTERFACE IMPORTED)

set_target_properties(GEOS::geos_cxx_flags PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "\$<\$<NOT:\$<CONFIG:Debug>>:NDEBUG>;USE_UNSTABLE_GEOS_CPP_API;HAVE_FENV"
  INTERFACE_COMPILE_FEATURES "cxx_std_17"
  INTERFACE_COMPILE_OPTIONS "\$<\$<OR:\$<CXX_COMPILER_ID:Clang>,\$<CXX_COMPILER_ID:AppleClang>>:-ffp-contract=off>;\$<\$<CXX_COMPILER_ID:GNU>:-ffp-contract=off>;\$<\$<BOOL:>:/fp:precise>;\$<\$<AND:\$<CXX_COMPILER_ID:GNU>,\$<EQUAL:4,8>>:-ffloat-store>"
)

# Create imported target GEOS::geos_developer_cxx_flags
add_library(GEOS::geos_developer_cxx_flags INTERFACE IMPORTED)

set_target_properties(GEOS::geos_developer_cxx_flags PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "\$<\$<BOOL:>:_CRT_NONSTDC_NO_DEPRECATE>;\$<\$<BOOL:>:_SCL_SECURE_NO_DEPRECATE>;\$<\$<BOOL:>:_CRT_SECURE_NO_WARNINGS>;\$<\$<BOOL:>:NOMINMAX>"
  INTERFACE_COMPILE_OPTIONS "\$<\$<CXX_COMPILER_ID:MSVC>:-W4>;\$<\$<OR:\$<CXX_COMPILER_ID:GNU>,\$<CXX_COMPILER_ID:Clang>,\$<CXX_COMPILER_ID:AppleClang>>:-Werror;-pedantic;-Wall;-Wextra;-Wno-long-long;-Wcast-align;-Wconversion;-Wsign-conversion;-Wchar-subscripts;-Wdouble-promotion;-Wpointer-arith;-Wformat;-Wformat-security;-Wshadow;-Wuninitialized;-Wunused-parameter;-fno-common>;\$<\$<CXX_COMPILER_ID:GNU>:-fno-implicit-inline-templates;-Wno-psabi;-Wsuggest-attribute=format>;\$<\$<OR:\$<CXX_COMPILER_ID:Clang>,\$<CXX_COMPILER_ID:AppleClang>>:-Wno-unknown-warning-option>;-Wsuggest-override"
)

# Import target "GEOS::ryu" for configuration "Release"
set_property(TARGET GEOS::ryu APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(GEOS::ryu PROPERTIES
  IMPORTED_COMMON_LANGUAGE_RUNTIME_RELEASE ""
  IMPORTED_OBJECTS_RELEASE "/home/maciek/Personal/aoc/geos-3.14.1/src/deps/CMakeFiles/ryu.dir/ryu/d2s.c.o"
  )

# Import target "GEOS::geos" for configuration "Release"
set_property(TARGET GEOS::geos APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(GEOS::geos PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/maciek/Personal/aoc/geos-3.14.1/lib/libgeos.so.3.14.1"
  IMPORTED_SONAME_RELEASE "libgeos.so.3.14.1"
  )

# Import target "GEOS::geos_c" for configuration "Release"
set_property(TARGET GEOS::geos_c APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(GEOS::geos_c PROPERTIES
  IMPORTED_LINK_DEPENDENT_LIBRARIES_RELEASE "GEOS::geos"
  IMPORTED_LOCATION_RELEASE "/home/maciek/Personal/aoc/geos-3.14.1/lib/libgeos_c.so.1.20.5"
  IMPORTED_SONAME_RELEASE "libgeos_c.so.1"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
